<template>

    <us-card title="PEM Public/private key">
        <us-card-body>

            <p>
                This is a tool that you can use to generate a symetric key pair that is suitable as an API key. 
                This creates a 4096 length PEM key. The public key is a SPKI key and the private key is PKCS8 encoded.                
            </p>

            <p>
                You do not have to use this tool, and are encouraged to generate your own keys. This is provided as a convenience.
            </p>

            <p>
                The key pairs generated by this key are not stored anywhere, so you'll need to store this information yourself if 
                you intend to use this tool. Copy and paste the keys into files and store somewhere safe!
            </p>

            <div>
                <us-button @click="generateKeys()"><i class="fas fa-key"></i> Generate</us-button>
            </div>
            
            <us-form-group label="Public Key" v-if="sampleKeyPair" help-text="This is your public key, and is used when you register an api key with this service.">
                <us-form-textarea v-model="sampleKeyPair.public"></us-form-textarea>
            </us-form-group>

            <us-form-group label="Private Key" v-if="sampleKeyPair" help-text="This is your private key, keep it safe!">
                <us-form-textarea v-model="sampleKeyPair.private"></us-form-textarea>
            </us-form-group>
            
        </us-card-body>
    </us-card>

</template>
<script>
import User from '../../../models/User';
export default {
    name: "key-generator",
    data(){
        return {
            sampleKeyPair: null
        }
    },   
    methods: {
        
        async generateKeys(){
            let user = new User();
            this.sampleKeyPair = await user.generatePEM();
        }        
    } 
};
</script>
<style lang="scss">
</style>
